//
// Created by amina on 8/2/2021.
//

#ifndef FS_PROGRAM_SCORE_CALCULATOR_LADIESSPWINDOW_H
#define FS_PROGRAM_SCORE_CALCULATOR_LADIESSPWINDOW_H


class LadiesSPWindow {

};


#endif //FS_PROGRAM_SCORE_CALCULATOR_LADIESSPWINDOW_H
