//
// Created by amina on 8/2/2021.
//

#ifndef FS_PROGRAM_SCORE_CALCULATOR_SCOREREPOSITORY_H
#define FS_PROGRAM_SCORE_CALCULATOR_SCOREREPOSITORY_H


class ScoreRepository {

};


#endif //FS_PROGRAM_SCORE_CALCULATOR_SCOREREPOSITORY_H
